[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#280f0fff"
secondaryBackgroundColor = "#41424aff"
textColor = "#d3d7ebff"
font = "sans serif"

[global]
developmentMode = false

[server]
maxUploadSize = 50000
headless = true
port = 8501
address = "127.0.0.1"
